POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "This blog is not authenticated",
  "author": "Not Authenticated",
  "url": "http://www.not.authenticated.example.com",
  "likes": "100"
}
